### ISSUE TITLE
reporte primera pratica cuestionario 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-jdgras#1]
[reporte pratica6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-jdgras/files/13221950/reporte.pratica6.pdf)

**Comment by yanet02** [comment]
Portada = 25% Excelente.
Procedimiento = 25% Muy bien hecho.
Figuras, ilustraciones y fotografías = 25% EXCELENTE
Resultados y conclusiones = 25%.
CALIFICACIÓN= 30/30.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
